# Generated by Django 5.2.3 on 2025-06-24 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacksystem', '0003_alter_user_options_user_manager_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('performance_period', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive Feedback'), ('constructive', 'Constructive Feedback'), ('recognition', 'Recognition'), ('development', 'Developmental Feedback')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-feedback_date'],
            },
        ),
    ]
