# Generated by Django 5.2.3 on 2025-06-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacksystem', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
