# Generated by Django 5.2.3 on 2025-06-24 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacksystem', '0005_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('performance_period', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive Feedback'), ('constructive', 'Constructive Feedback'), ('recognition', 'Recognition'), ('development', 'Developmental Feedback')], max_length=20)),
                ('key_strengths', models.TextField(choices=[('communication', 'Communication Skills'), ('teamwork', 'Teamwork and Collaboration'), ('problem_solving', 'Problem Solving'), ('leadership', 'Leadership'), ('technical_skills', 'Technical Skills'), ('adaptability', 'Adaptability'), ('initiative', 'Initiative'), ('time_management', 'Time Management')], max_length=500)),
                ('areas_for_improvement', models.TextField(default='To be updated')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-feedback_date'],
            },
        ),
    ]
